### ISSUE TITLE
euh

### ISSUE THREAD

**Issue by nasslamenace** [Chtwin/Lubrisoft_arene#2]
si enfaite y'a un autre petit probleme... dans votre dossier il n'y pas les fichiers suivant:
-jeu.h
-jeu.c
-main.h
vous pouvez regler ça svp ?

**Comment by Chtwin** [comment]
Non, c'est normal ces fichiers ont été supprimé mais j'ai oublié de les dissocier du fichier projet. Oubliez les le programme fonctionne sans.

**Comment by nasslamenace** [comment]
ah d'accord merci
