### ISSUE TITLE
Tableau des scores buggué

### ISSUE THREAD

**Issue by vicmat999** [Chtwin/Lubrisoft_arene#3]
A la fin de la partie (5 joueurs) il y a deux personnes en 5ème position et aucune permière position, alors que personne n'a le même nombre de point.
Je vous envoie aussi un screenshot (mon ordi est pas adapté donc l'image n'est pas entière).

Victor MATHIEU
![bug](https://user-images.githubusercontent.com/38254256/38563826-15c6c036-3cde-11e8-9114-f560f1c59415.png)

**Comment by Chtwin** [comment]
Oui c'est tout à fait normal ,car comme je l'ai précisé dans les commits le classement fonctionne si il ne reste qu'un survivant. En ce qui concerne classement avec le nombre de rubis, sil il y a plusieurs survivants je le mettrai au point dès que possible.

**Comment by Naegon** [comment]
Je pense que le problème est lié à **mac** et à votre façon d'utiliser les variables
Quand je lance le jeux, la fin de partie apparait tout de suite, j'ai un nombre de points astronomique et on m'annonce que je suis actuellement au tour n859191098 ce qui me semble excessif

![sans titre](https://user-images.githubusercontent.com/36730988/38683194-2e93e798-3e6d-11e8-92a9-fc44f607484f.png)

_Guillaume Hamel_

**Comment by Chtwin** [comment]
le bug est normalement fix
