### ISSUE TITLE
Problème score début de partie

### ISSUE THREAD

**Issue by ghost** [Chtwin/Lubrisoft_arene#4]
Bonjour ,

J'ai rencontré un bug qui faisait que les IA commençaient avec un nombre différent de rubis ( IA1 = 25 et IA 2 = 26). Si je me souviens bien , toutes les IA commencent avec le même nombre de rubis. Je ne sais pas si le problème vient de mon ordi ou pas.
Je reste à votre disposition.

Cordialement
LE DEUF Alexandre.

**Comment by Chtwin** [comment]
C'est normal chaque joueur commence avec 25 rubis + 1 à 3 rubis de manière aléatoire.
